-- TikTok account binding reliability upgrade.
-- Scope: run on the test database first. Production migration is a separate release step.

ALTER TABLE public.tiktok_auth_states
  ALTER COLUMN code_verifier DROP NOT NULL;

ALTER TABLE public.tiktok_auth_states
  ADD COLUMN IF NOT EXISTS flow_type TEXT NOT NULL DEFAULT 'web',
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS ip_hash TEXT,
  ADD COLUMN IF NOT EXISTS user_agent_hash TEXT,
  ADD COLUMN IF NOT EXISTS client_ticket TEXT,
  ADD COLUMN IF NOT EXISTS qr_token TEXT,
  ADD COLUMN IF NOT EXISTS last_checked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS error_code TEXT,
  ADD COLUMN IF NOT EXISTS error_message TEXT;

ALTER TABLE public.tiktok_auth_states
  DROP CONSTRAINT IF EXISTS tiktok_auth_states_flow_type_check,
  ADD CONSTRAINT tiktok_auth_states_flow_type_check
    CHECK (flow_type IN ('web', 'qr', 'shop'));

ALTER TABLE public.tiktok_auth_states
  DROP CONSTRAINT IF EXISTS tiktok_auth_states_status_check,
  ADD CONSTRAINT tiktok_auth_states_status_check
    CHECK (status IN ('pending', 'completed', 'failed', 'expired'));

CREATE INDEX IF NOT EXISTS idx_tiktok_auth_states_user_created
  ON public.tiktok_auth_states(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tiktok_auth_states_ip_ua_created
  ON public.tiktok_auth_states(ip_hash, user_agent_hash, created_at DESC)
  WHERE ip_hash IS NOT NULL AND user_agent_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tiktok_auth_states_pending_expiry
  ON public.tiktok_auth_states(status, expires_at)
  WHERE status = 'pending';

ALTER TABLE public.tiktok_accounts
  ADD COLUMN IF NOT EXISTS access_token_expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS creator_info_cache JSONB,
  ADD COLUMN IF NOT EXISTS creator_info_cached_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_tiktok_accounts_access_token_expires_at
  ON public.tiktok_accounts(access_token_expires_at)
  WHERE access_token_expires_at IS NOT NULL;

CREATE OR REPLACE FUNCTION public.cleanup_expired_auth_states()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.tiktok_auth_states
  SET status = 'expired',
      error_code = COALESCE(error_code, 'expired'),
      error_message = COALESCE(error_message, 'Authorization session expired.'),
      code_verifier = NULL,
      client_ticket = NULL,
      qr_token = NULL
  WHERE status = 'pending'
    AND expires_at < NOW();

  DELETE FROM public.tiktok_auth_states
  WHERE created_at < NOW() - INTERVAL '7 days'
    AND status IN ('completed', 'failed', 'expired');

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

COMMENT ON COLUMN public.tiktok_auth_states.flow_type IS 'TikTok authorization flow type: web, qr, or shop.';
COMMENT ON COLUMN public.tiktok_auth_states.status IS 'Authorization session status for cooldown and diagnostics.';
COMMENT ON COLUMN public.tiktok_auth_states.ip_hash IS 'One-way hashed client IP for abuse diagnostics; raw IP is not stored.';
COMMENT ON COLUMN public.tiktok_auth_states.user_agent_hash IS 'One-way hashed user agent for abuse diagnostics; raw user agent is not stored.';
COMMENT ON COLUMN public.tiktok_auth_states.client_ticket IS 'QR authorization integrity ticket generated by this service.';
COMMENT ON COLUMN public.tiktok_auth_states.qr_token IS 'TikTok QR status token returned by get_qrcode.';
COMMENT ON COLUMN public.tiktok_accounts.access_token_expires_at IS 'Access token expiry. token_expires_at remains the user-visible refresh authorization expiry.';
COMMENT ON COLUMN public.tiktok_accounts.creator_info_cache IS 'Short-lived cached TikTok creator_info response.';
COMMENT ON COLUMN public.tiktok_accounts.creator_info_cached_at IS 'Timestamp for creator_info_cache.';
