-- TikTok multi-task publishing support.
-- Scope: test database first. Keep the existing single-create flow intact.

ALTER TABLE public.publish_tasks
  ADD COLUMN IF NOT EXISTS workflow TEXT NOT NULL DEFAULT 'standard',
  ADD COLUMN IF NOT EXISTS source_account_group_id UUID REFERENCES public.tiktok_account_groups(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS plan_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS idempotency_key TEXT,
  ADD COLUMN IF NOT EXISTS published_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pending_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_views INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_likes INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.publish_task_items
  ADD COLUMN IF NOT EXISTS cover_timestamp_ms INTEGER,
  ADD COLUMN IF NOT EXISTS tiktok_video_id TEXT,
  ADD COLUMN IF NOT EXISTS view_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS like_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS comment_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS share_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stats_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS plan_sequence INTEGER,
  ADD COLUMN IF NOT EXISTS plan_round INTEGER,
  ADD COLUMN IF NOT EXISTS plan_account_position INTEGER,
  ADD COLUMN IF NOT EXISTS source_video_id TEXT,
  ADD COLUMN IF NOT EXISTS source_video_name TEXT,
  ADD COLUMN IF NOT EXISTS dedupe_key TEXT;

DO $$
DECLARE
  v_constraint_name TEXT;
BEGIN
  FOR v_constraint_name IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.publish_tasks'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%status%'
  LOOP
    EXECUTE format('ALTER TABLE public.publish_tasks DROP CONSTRAINT IF EXISTS %I', v_constraint_name);
  END LOOP;
END;
$$;

ALTER TABLE public.publish_tasks
  ADD CONSTRAINT publish_tasks_status_check
  CHECK (status IN ('pending', 'scheduled', 'running', 'completed', 'partial_failed', 'failed', 'cancelled'));

ALTER TABLE public.publish_tasks
  DROP CONSTRAINT IF EXISTS publish_tasks_workflow_check;

ALTER TABLE public.publish_tasks
  ADD CONSTRAINT publish_tasks_workflow_check
  CHECK (workflow IN ('standard', 'multi_task'));

DO $$
DECLARE
  v_constraint_name TEXT;
BEGIN
  FOR v_constraint_name IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.publish_task_items'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%status%'
  LOOP
    EXECUTE format('ALTER TABLE public.publish_task_items DROP CONSTRAINT IF EXISTS %I', v_constraint_name);
  END LOOP;
END;
$$;

ALTER TABLE public.publish_task_items
  ADD CONSTRAINT publish_task_items_status_check
  CHECK (status IN ('pending', 'scheduled', 'processing', 'uploading', 'published', 'failed', 'cancelled'));

CREATE INDEX IF NOT EXISTS idx_publish_tasks_user_workflow_created
  ON public.publish_tasks(user_id, workflow, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_publish_tasks_multi_group
  ON public.publish_tasks(source_account_group_id)
  WHERE workflow = 'multi_task';

CREATE UNIQUE INDEX IF NOT EXISTS idx_publish_tasks_user_idempotency
  ON public.publish_tasks(user_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_publish_task_items_plan_sequence
  ON public.publish_task_items(task_id, plan_sequence);

CREATE INDEX IF NOT EXISTS idx_publish_task_items_due_schedule
  ON public.publish_task_items(scheduled_at, plan_sequence)
  WHERE status = 'scheduled';

CREATE UNIQUE INDEX IF NOT EXISTS idx_publish_task_items_dedupe
  ON public.publish_task_items(task_id, dedupe_key)
  WHERE dedupe_key IS NOT NULL;

COMMENT ON COLUMN public.publish_tasks.workflow IS 'standard or multi_task workflow marker.';
COMMENT ON COLUMN public.publish_tasks.source_account_group_id IS 'Account group selected for multi-task publishing.';
COMMENT ON COLUMN public.publish_tasks.plan_config IS 'Frozen assignment, schedule, defaults, and preview metadata.';
COMMENT ON COLUMN public.publish_tasks.idempotency_key IS 'Client request key used to prevent duplicate task creation.';
COMMENT ON COLUMN public.publish_task_items.plan_sequence IS 'Overall execution order generated by the multi-task scheduler.';
COMMENT ON COLUMN public.publish_task_items.plan_round IS 'Round number per account generated by the multi-task scheduler.';
COMMENT ON COLUMN public.publish_task_items.plan_account_position IS 'Account order inside the selected group.';
COMMENT ON COLUMN public.publish_task_items.source_video_id IS 'Client or asset video identifier.';
COMMENT ON COLUMN public.publish_task_items.source_video_name IS 'Original source video name.';
COMMENT ON COLUMN public.publish_task_items.dedupe_key IS 'Per-task unique key for video-account assignment.';
